name: virtual-machine-manager

services:
  development:
    hostname: virtual-machine-manager.local
    image: ghcr.io/viral32111/virtual-machine-manager-development-environment:latest
    pull_policy: always
    build:
      pull: true
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      # VNC
      - target: 5900
        published: 5900
        host_ip: 127.0.0.1
        protocol: tcp
    extra_hosts:
      - host.docker.internal:host-gateway # Access to services on host
    volumes:
      # Visual Studio Code
      - type: volume
        source: vscode-server
        target: /home/user/.vscode-server
      - type: volume
        source: vscode-server-insiders
        target: /home/user/.vscode-server-insiders

      # Repository
      - type: bind
        source: ../
        target: /home/user/repository

volumes:
  vscode-server:
  vscode-server-insiders:

networks:
  internal:
    driver: bridge
