name: email
uuid: 000000000000-0000-0000-00000000

architecture: x86_64

kvm: true
machine:
  type: q35
  acceleration: kvm

processor:
  cpu: host
  sockets: 1
  cores: 4
  threads: 2

memory:
  size: 8192
  balloon: false

uefi: true

rtc: utc

tpm: 2.0

disks:
  - image: images/debian-12.iso

drives:
  - image: ${uuid}/drives/primary.qcow2
    size: 8192
    format: qcow2
    preallocate: true
    interface: nvme

boot: drive

serial: pty
monitor: pty

vnc:
  address: 0.0.0.0
  id: 1
  password: p4ssw0rd

networks:
  - type: user
    range: 172.28.1.0/24
    model: e1000
    mac: 00:11:22:33:44:55

  - type: bridge
    bridge: br0

keyboard: en-gb
