name: CI

on:
  push:
    paths:
      - '**'
    branches:
      - '**'
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    strategy:
      matrix:
        configuration:
          - debug
          - release
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Make
        run: make ${{ matrix.configuration }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}
          path: build/${{ matrix.configuration }}

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          path: build

      - name: Bundle build artifact
        run: zip -r ${{ github.ref_name }}.zip build

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          files: ${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
